"""baseline schema per ARCH.md section 11

Revision ID: 0001
Revises:
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adjudications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("identity_kind", sa.String(length=16), nullable=False),
        sa.Column("identity_key", sa.String(length=128), nullable=False),
        sa.Column("attribute", sa.String(length=16), nullable=False),
        sa.Column("value", sa.String(length=64), nullable=False),
        sa.Column(
            "reviewed_values_json",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.Column("adjudicated_by", sa.String(length=128), nullable=False),
        sa.Column("adjudicated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_adjudications_identity_key"), "adjudications", ["identity_key"], unique=False
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("subject", sa.String(length=256), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "detail_json",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_table(
        "scan_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("target_ref", sa.Text(), nullable=False),
        sa.Column("started", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("policy_snapshot_id", sa.String(length=64), nullable=False),
        sa.Column(
            "policy_snapshot_json",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.Column("z_scenario", sa.String(length=64), nullable=False),
        sa.Column("as_of", sa.String(length=10), nullable=False),
        sa.Column(
            "summary_json",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "stages_json",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scan_runs_status"), "scan_runs", ["status"], unique=False)
    op.create_table(
        "suppressions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("asset_identity_key", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("author", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_suppressions_asset_identity_key"),
        "suppressions",
        ["asset_identity_key"],
        unique=False,
    )
    op.create_table(
        "systems",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("owner", sa.Text(), nullable=False),
        sa.Column("criticality", sa.Integer(), nullable=False),
        sa.Column("data_class", sa.String(length=24), nullable=False),
        sa.Column("retention_years", sa.Float(), nullable=False),
        sa.Column("retention_inferred", sa.Boolean(), nullable=False),
        sa.Column("internet_facing", sa.Boolean(), nullable=False),
        sa.Column(
            "regimes_json",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "bindings_json",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "collector_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scan_run_id", sa.String(length=36), nullable=False),
        sa.Column("collector", sa.String(length=64), nullable=False),
        sa.Column("tool_version", sa.String(length=64), nullable=False),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("raw_uri", sa.Text(), nullable=True),
        sa.Column("partial", sa.Boolean(), nullable=False),
        sa.Column(
            "errors_json",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=True,
        ),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["scan_run_id"],
            ["scan_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_collector_runs_scan_run_id"), "collector_runs", ["scan_run_id"], unique=False
    )
    op.create_table(
        "crypto_assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scan_run_id", sa.String(length=36), nullable=False),
        sa.Column("identity_kind", sa.String(length=16), nullable=False),
        sa.Column("identity_key", sa.String(length=128), nullable=False),
        sa.Column("asset_type", sa.String(length=32), nullable=False),
        sa.Column("function", sa.String(length=32), nullable=True),
        sa.Column("family", sa.String(length=128), nullable=False),
        sa.Column("parameter_set", sa.String(length=64), nullable=True),
        sa.Column("curve", sa.String(length=128), nullable=True),
        sa.Column("mode", sa.String(length=32), nullable=True),
        sa.Column("padding", sa.String(length=32), nullable=True),
        sa.Column("oid", sa.String(length=128), nullable=True),
        sa.Column("finding_class", sa.String(length=24), nullable=False),
        sa.Column("migration_authority", sa.String(length=32), nullable=False),
        sa.Column("authority_basis", sa.Text(), nullable=False),
        sa.Column("concluded_tier", sa.Integer(), nullable=False),
        sa.Column("disputed", sa.Boolean(), nullable=False),
        sa.Column(
            "disputes_json",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scan_run_id"],
            ["scan_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_assets_scan_authority",
        "crypto_assets",
        ["scan_run_id", "migration_authority"],
        unique=False,
    )
    op.create_index(
        "ix_assets_scan_class", "crypto_assets", ["scan_run_id", "finding_class"], unique=False
    )
    op.create_index(
        "ix_assets_scan_disputed", "crypto_assets", ["scan_run_id", "disputed"], unique=False
    )
    op.create_index(
        "ix_assets_scan_family", "crypto_assets", ["scan_run_id", "family"], unique=False
    )
    op.create_index(
        "ix_assets_scan_identity", "crypto_assets", ["scan_run_id", "identity_key"], unique=False
    )
    op.create_table(
        "migration_edges",
        sa.Column("scan_run_id", sa.String(length=36), nullable=False),
        sa.Column("from_unit_id", sa.String(length=256), nullable=False),
        sa.Column("to_unit_id", sa.String(length=256), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["scan_run_id"],
            ["scan_runs.id"],
        ),
        sa.PrimaryKeyConstraint("scan_run_id", "from_unit_id", "to_unit_id", "kind"),
    )
    op.create_table(
        "migration_units",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("scan_run_id", sa.String(length=36), nullable=False),
        sa.Column("system_id", sa.String(length=128), nullable=False),
        sa.Column("function", sa.String(length=32), nullable=False),
        sa.Column("wave", sa.Integer(), nullable=True),
        sa.Column("target_quarter", sa.String(length=10), nullable=True),
        sa.Column("feasible", sa.Boolean(), nullable=False),
        sa.Column("schedule_risk", sa.String(length=16), nullable=True),
        sa.ForeignKeyConstraint(
            ["scan_run_id"],
            ["scan_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id", "scan_run_id"),
    )
    op.create_table(
        "system_deps",
        sa.Column("from_system_id", sa.String(length=128), nullable=False),
        sa.Column("to_system_id", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_system_id"],
            ["systems.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_system_id"],
            ["systems.id"],
        ),
        sa.PrimaryKeyConstraint("from_system_id", "to_system_id"),
    )
    op.create_table(
        "asset_systems",
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("system_id", sa.String(length=128), nullable=False),
        sa.Column(
            "basis_json",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["crypto_assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
        ),
        sa.PrimaryKeyConstraint("asset_id", "system_id"),
    )
    op.create_index(
        op.f("ix_asset_systems_system_id"), "asset_systems", ["system_id"], unique=False
    )
    op.create_table(
        "occurrences",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("collector_run_id", sa.String(length=36), nullable=True),
        sa.Column("collector", sa.String(length=64), nullable=False),
        sa.Column("tool_version", sa.String(length=64), nullable=False),
        sa.Column("locus_type", sa.String(length=24), nullable=False),
        sa.Column(
            "locus_json",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("detection_method", sa.String(length=64), nullable=False),
        sa.Column("raw_ref", sa.Text(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["crypto_assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["collector_run_id"],
            ["collector_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_occurrences_asset_id"), "occurrences", ["asset_id"], unique=False)
    op.create_table(
        "recommendations",
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("target_algorithm", sa.String(length=128), nullable=True),
        sa.Column(
            "rationale_json",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["crypto_assets.id"],
        ),
        sa.PrimaryKeyConstraint("asset_id"),
    )
    op.create_table(
        "risk_scores",
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("system_id", sa.String(length=128), nullable=False),
        sa.Column("scan_run_id", sa.String(length=36), nullable=False),
        sa.Column("policy_snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("band", sa.String(length=24), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("mosca_gap", sa.Float(), nullable=True),
        sa.Column("ev", sa.Float(), nullable=True),
        sa.Column("z_effective", sa.String(length=10), nullable=True),
        sa.Column("z_source", sa.String(length=128), nullable=True),
        sa.Column(
            "entry_json",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["crypto_assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scan_run_id"],
            ["scan_runs.id"],
        ),
        sa.PrimaryKeyConstraint("asset_id", "system_id"),
    )
    op.create_index("ix_scores_scan_band", "risk_scores", ["scan_run_id", "band"], unique=False)
    op.create_index(
        "ix_scores_scan_outcome", "risk_scores", ["scan_run_id", "outcome"], unique=False
    )
    op.create_index(
        "ix_scores_scan_system", "risk_scores", ["scan_run_id", "system_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_scores_scan_system", table_name="risk_scores")
    op.drop_index("ix_scores_scan_outcome", table_name="risk_scores")
    op.drop_index("ix_scores_scan_band", table_name="risk_scores")
    op.drop_table("risk_scores")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_occurrences_asset_id"), table_name="occurrences")
    op.drop_table("occurrences")
    op.drop_index(op.f("ix_asset_systems_system_id"), table_name="asset_systems")
    op.drop_table("asset_systems")
    op.drop_table("system_deps")
    op.drop_table("migration_units")
    op.drop_table("migration_edges")
    op.drop_index("ix_assets_scan_identity", table_name="crypto_assets")
    op.drop_index("ix_assets_scan_family", table_name="crypto_assets")
    op.drop_index("ix_assets_scan_disputed", table_name="crypto_assets")
    op.drop_index("ix_assets_scan_class", table_name="crypto_assets")
    op.drop_index("ix_assets_scan_authority", table_name="crypto_assets")
    op.drop_table("crypto_assets")
    op.drop_index(op.f("ix_collector_runs_scan_run_id"), table_name="collector_runs")
    op.drop_table("collector_runs")
    op.drop_table("systems")
    op.drop_index(op.f("ix_suppressions_asset_identity_key"), table_name="suppressions")
    op.drop_table("suppressions")
    op.drop_index(op.f("ix_scan_runs_status"), table_name="scan_runs")
    op.drop_table("scan_runs")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_adjudications_identity_key"), table_name="adjudications")
    op.drop_table("adjudications")
    # ### end Alembic commands ###
