"""Builds real Java artefacts for T-036a's tests: a genuinely compiled
`.class` file (via the system `javac`) packaged into a real JAR/WAR (via
`zipfile`, which is exactly what a JAR is).

A hand-crafted byte blob would not prove the constant-pool parser is
right — the parts most likely to be wrong (the `CONSTANT_Long`/
`CONSTANT_Double` two-slot rule, the real tag mix `javac` emits) only
show up in output from a real compiler."""

from __future__ import annotations

import shutil
import subprocess
import zipfile
from pathlib import Path

JAVAC_AVAILABLE = shutil.which("javac") is not None

CRYPTO_DEMO_SOURCE = """
import javax.crypto.Cipher;
import java.security.MessageDigest;

public class CryptoDemo {
    public byte[] work(byte[] data) throws Exception {
        Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
        MessageDigest digest = MessageDigest.getInstance("SHA-256");
        long forcesConstantLong = 1234567890123L;
        double forcesConstantDouble = 3.14159;
        return digest.digest(data);
    }
}
"""

NO_CRYPTO_SOURCE = """
public class PlainDemo {
    public int add(int a, int b) {
        return a + b;
    }
}
"""


def compile_class(source: str, class_name: str, *, tmp_path: Path) -> bytes:
    """Compiles `source` with the real `javac` and returns the resulting
    class file's bytes."""
    work_dir = tmp_path / f"javac-{class_name}"
    work_dir.mkdir(parents=True, exist_ok=True)
    source_path = work_dir / f"{class_name}.java"
    source_path.write_text(source)
    subprocess.run(["javac", str(source_path)], capture_output=True, check=True, cwd=work_dir)
    return (work_dir / f"{class_name}.class").read_bytes()


def build_jar(entries: dict[str, bytes], *, path: Path, compress: bool = True) -> Path:
    """Writes a real ZIP-format archive — which is all a JAR/WAR is."""
    mode = zipfile.ZIP_DEFLATED if compress else zipfile.ZIP_STORED
    with zipfile.ZipFile(path, "w", mode) as archive:
        for name, data in entries.items():
            archive.writestr(name, data)
    return path


MANIFEST = (
    b"Manifest-Version: 1.0\r\n"
    b"Created-By: QAVACH test fixture\r\n"
    b"Implementation-Title: payments-service\r\n"
    b"Implementation-Version: 4.2.1\r\n"
    b"\r\n"
)

BOUNCYCASTLE_POM_PROPERTIES = (
    b"#Generated by Maven\ngroupId=org.bouncycastle\nartifactId=bcprov-jdk18on\nversion=1.78\n"
)
